import {
  Cycle,
  Deployment,
  EnvTopology,
  UpgradeAction,
} from './models';

/**
 * Mock layer.
 *
 * Exported straight out of the seeded PostgreSQL database on 2026-09-18, so
 * every date here is a real published endoflife.date value and every shape
 * matches what the API will return. Replacing this file with generated HTTP
 * calls changes no component.
 */

export const CYCLES: Cycle[] = [
  {
    id: 'kafka-3-8',
    technology: 'Apache Kafka',
    componentType: 'MESSAGING',
    cycle: '3.8',
    label: '3.8',
    releaseDate: '2024-07-26',
    eolDate: '2024-11-06',
    activeSupportEnd: null,
    isLts: false,
    isMaintained: false,
    latestPatch: '3.8.1',
    eolSource: 'API',
    versions: ['3.8.1'],
  },
  {
    id: 'docker-28',
    technology: 'Docker Engine',
    componentType: 'CONTAINER',
    cycle: '28',
    label: '28',
    releaseDate: '2025-02-20',
    eolDate: '2026-05-13',
    activeSupportEnd: null,
    isLts: false,
    isMaintained: false,
    latestPatch: '28.5.2',
    eolSource: 'API',
    versions: ['28.5.2'],
  },
  {
    id: 'node-25',
    technology: 'Node.js',
    componentType: 'RUNTIME',
    cycle: '25',
    label: '25',
    releaseDate: '2025-10-15',
    eolDate: '2026-06-01',
    activeSupportEnd: '2026-04-01',
    isLts: false,
    isMaintained: false,
    latestPatch: '25.9.0',
    eolSource: 'API',
    versions: ['25.9.0'],
  },
  {
    id: 'mongodb-8-2',
    technology: 'MongoDB',
    componentType: 'DATABASE',
    cycle: '8.2',
    label: '8.2',
    releaseDate: '2025-09-30',
    eolDate: '2026-07-31',
    activeSupportEnd: null,
    isLts: false,
    isMaintained: false,
    latestPatch: '8.2.12',
    eolSource: 'API',
    versions: ['8.2.12', '8.2.4'],
  },
  {
    id: 'openssl-3-6',
    technology: 'OpenSSL',
    componentType: 'LIBRARY',
    cycle: '3.6',
    label: '3.6',
    releaseDate: '2025-10-01',
    eolDate: '2026-11-01',
    activeSupportEnd: null,
    isLts: false,
    isMaintained: false,
    latestPatch: '3.6.4',
    eolSource: 'API',
    versions: ['3.6.4'],
  },
  {
    id: 'angular-20',
    technology: 'Angular',
    componentType: 'FRAMEWORK',
    cycle: '20',
    label: '20',
    releaseDate: '2025-05-28',
    eolDate: '2026-11-28',
    activeSupportEnd: '2025-11-19',
    isLts: false,
    isMaintained: true,
    latestPatch: '20.3.31',
    eolSource: 'API',
    versions: ['20.3.31'],
  },
  {
    id: 'k8s-1-35',
    technology: 'Kubernetes',
    componentType: 'ORCHESTRATION',
    cycle: '1.35',
    label: '1.35',
    releaseDate: '2025-12-17',
    eolDate: '2027-02-28',
    activeSupportEnd: '2026-12-28',
    isLts: false,
    isMaintained: true,
    latestPatch: '1.35.8',
    eolSource: 'API',
    versions: ['1.35.8'],
  },
  {
    id: 'angular-21',
    technology: 'Angular',
    componentType: 'FRAMEWORK',
    cycle: '21',
    label: '21',
    releaseDate: '2025-11-19',
    eolDate: '2027-06-30',
    activeSupportEnd: '2026-06-03',
    isLts: false,
    isMaintained: true,
    latestPatch: '21.2.23',
    eolSource: 'API',
    versions: ['21.2.23'],
  },
  {
    id: 'node-24',
    technology: 'Node.js',
    componentType: 'RUNTIME',
    cycle: '24',
    label: '24 (LTS)',
    releaseDate: '2025-05-06',
    eolDate: '2028-04-30',
    activeSupportEnd: '2026-10-20',
    isLts: true,
    isMaintained: true,
    latestPatch: '24.21.0',
    eolSource: 'API',
    versions: ['24.21.0'],
  },
  {
    id: 'postgres-16',
    technology: 'PostgreSQL',
    componentType: 'DATABASE',
    cycle: '16',
    label: '16',
    releaseDate: '2023-09-14',
    eolDate: '2028-11-09',
    activeSupportEnd: null,
    isLts: false,
    isMaintained: true,
    latestPatch: '16.15',
    eolSource: 'API',
    versions: ['16.15'],
  },
  {
    id: 'mongodb-8-3',
    technology: 'MongoDB',
    componentType: 'DATABASE',
    cycle: '8.3',
    label: '8.3',
    releaseDate: '2026-05-31',
    eolDate: '2029-10-31',
    activeSupportEnd: null,
    isLts: false,
    isMaintained: true,
    latestPatch: '8.3.11',
    eolSource: 'API',
    versions: ['8.3.11'],
  },
  {
    id: 'openssl-3-5',
    technology: 'OpenSSL',
    componentType: 'LIBRARY',
    cycle: '3.5',
    label: '3.5',
    releaseDate: '2025-04-08',
    eolDate: '2030-04-08',
    activeSupportEnd: null,
    isLts: true,
    isMaintained: true,
    latestPatch: '3.5.8',
    eolSource: 'API',
    versions: ['3.5.8'],
  },
  {
    id: 'rhel-9',
    technology: 'RHEL',
    componentType: 'OS',
    cycle: '9',
    label: '9',
    releaseDate: '2022-05-18',
    eolDate: '2032-05-31',
    activeSupportEnd: '2027-05-31',
    isLts: false,
    isMaintained: true,
    latestPatch: '9.8',
    eolSource: 'API',
    versions: ['9.8', '9.6'],
  },
];

const LIME_DEFAULTS: Deployment['components'] = [
  { technology: 'MongoDB', version: '8.2.12', source: 'LIME_DEFAULT' },
  { technology: 'Node.js', version: '24.21.0', source: 'LIME_DEFAULT' },
  { technology: 'Angular', version: '20.3.31', source: 'LIME_DEFAULT' },
  { technology: 'Kubernetes', version: '1.35.8', source: 'LIME_DEFAULT' },
  { technology: 'RHEL', version: '9.8', source: 'LIME_DEFAULT' },
  { technology: 'Apache Kafka', version: '3.8.1', source: 'LIME_DEFAULT' },
  { technology: 'OpenSSL', version: '3.6.4', source: 'LIME_DEFAULT' },
];

export const DEPLOYMENTS: Deployment[] = [
  {
    id: 'acme-prod',
    projectId: 'acme',
    customer: 'Acme Bank',
    customerCode: 'ACME',
    name: 'Acme Production',
    environment: 'PROD',
    location: 'EC2',
    locationDetail: 'eu-west-1',
    limeVersion: '2026.1',
    owners: ['DevOps', 'Platform'],
    components: LIME_DEFAULTS,
  },
  {
    id: 'acme-uat',
    projectId: 'acme',
    customer: 'Acme Bank',
    customerCode: 'ACME',
    name: 'Acme UAT',
    environment: 'UAT',
    location: 'EC2',
    locationDetail: 'eu-west-1',
    limeVersion: '2026.1',
    owners: ['DevOps'],
    components: LIME_DEFAULTS,
  },
  {
    id: 'nwnd-prod',
    projectId: 'nwnd',
    customer: 'Northwind Insurance',
    customerCode: 'NWND',
    name: 'Northwind Production',
    environment: 'PROD',
    location: 'CUSTOMER_SITE',
    locationDetail: 'Northwind DC, Colombo',
    limeVersion: '2026.1',
    owners: ['Platform'],
    // MongoDB overridden: this customer already moved to 8.3.
    components: [
      { technology: 'MongoDB', version: '8.3.11', source: 'OVERRIDE' },
      ...LIME_DEFAULTS.filter((c) => c.technology !== 'MongoDB'),
    ],
  },
  {
    id: 'nwnd-dev',
    projectId: 'nwnd',
    customer: 'Northwind Insurance',
    customerCode: 'NWND',
    name: 'Northwind DEV',
    environment: 'DEV',
    location: 'CUSTOMER_SITE',
    locationDetail: 'Northwind DC, Colombo',
    limeVersion: '2026.1',
    owners: ['Platform'],
    components: LIME_DEFAULTS,
  },
];

/**
 * Environment topologies — the part DevOps owns.
 *
 * Each node lists the technologies installed on it; the UI resolves every
 * entry against the registry to colour it by EOL risk. Positions live in the
 * data so an arrangement survives a reload and round-trips through JSON.
 */
export const TOPOLOGIES: EnvTopology[] = [
  {
    deploymentId: 'acme-prod',
    nodes: [
      {
        id: 'edge',
        name: 'Edge / TLS',
        role: 'gateway',
        host: '10.20.0.10',
        x: 40,
        y: 150,
        stack: [
          { technology: 'RHEL', version: '9.8' },
          { technology: 'OpenSSL', version: '3.6.4' },
        ],
      },
      {
        id: 'k8s',
        name: 'Kubernetes cluster',
        role: 'platform',
        host: 'eks-acme-prod',
        x: 330,
        y: 30,
        stack: [
          { technology: 'Kubernetes', version: '1.35.8' },
          { technology: 'Docker Engine', version: '28.5.2' },
        ],
      },
      {
        id: 'app',
        name: 'Lime application ×4',
        role: 'application',
        host: 'app-pool',
        x: 330,
        y: 220,
        stack: [
          { technology: 'Node.js', version: '24.21.0' },
          { technology: 'Angular', version: '20.3.31' },
        ],
      },
      {
        id: 'mongo',
        name: 'MongoDB replica set',
        role: 'database',
        host: '10.20.2.20-22',
        x: 640,
        y: 120,
        stack: [
          { technology: 'MongoDB', version: '8.2.12' },
          { technology: 'RHEL', version: '9.8' },
        ],
      },
      {
        id: 'kafka',
        name: 'Kafka brokers ×3',
        role: 'messaging',
        host: '10.20.3.30-32',
        x: 640,
        y: 320,
        stack: [{ technology: 'Apache Kafka', version: '3.8.1' }],
      },
    ],
    links: [
      { from: 'edge', to: 'app', label: 'https' },
      { from: 'k8s', to: 'app', label: 'hosts' },
      { from: 'app', to: 'mongo', label: 'mongodb' },
      { from: 'app', to: 'kafka', label: 'kafka' },
    ],
  },
  {
    deploymentId: 'acme-uat',
    nodes: [
      {
        id: 'app',
        name: 'Lime application ×2',
        role: 'application',
        host: 'uat-app',
        x: 80,
        y: 120,
        stack: [
          { technology: 'Node.js', version: '24.21.0' },
          { technology: 'Angular', version: '20.3.31' },
          { technology: 'RHEL', version: '9.8' },
        ],
      },
      {
        id: 'mongo',
        name: 'MongoDB single',
        role: 'database',
        host: 'uat-db',
        x: 430,
        y: 60,
        stack: [{ technology: 'MongoDB', version: '8.2.12' }],
      },
      {
        id: 'kafka',
        name: 'Kafka single',
        role: 'messaging',
        host: 'uat-kafka',
        x: 430,
        y: 250,
        stack: [{ technology: 'Apache Kafka', version: '3.8.1' }],
      },
    ],
    links: [
      { from: 'app', to: 'mongo' },
      { from: 'app', to: 'kafka' },
    ],
  },
  {
    deploymentId: 'nwnd-prod',
    nodes: [
      {
        id: 'edge',
        name: 'Customer gateway',
        role: 'gateway',
        host: 'nw-edge-01',
        x: 40,
        y: 140,
        stack: [
          { technology: 'RHEL', version: '9.8' },
          { technology: 'OpenSSL', version: '3.6.4' },
        ],
      },
      {
        id: 'app',
        name: 'Lime application ×2',
        role: 'application',
        host: 'nw-app-01/02',
        x: 330,
        y: 140,
        stack: [
          { technology: 'Node.js', version: '24.21.0' },
          { technology: 'Angular', version: '20.3.31' },
        ],
      },
      {
        id: 'mongo',
        name: 'MongoDB replica set',
        role: 'database',
        host: 'nw-db-01/02',
        x: 640,
        y: 60,
        // Overridden away from the Lime default of 8.2.12.
        stack: [{ technology: 'MongoDB', version: '8.3.11' }],
      },
      {
        id: 'kafka',
        name: 'Kafka brokers ×3',
        role: 'messaging',
        host: 'nw-kafka-01..03',
        x: 640,
        y: 280,
        stack: [{ technology: 'Apache Kafka', version: '3.8.1' }],
      },
    ],
    links: [
      { from: 'edge', to: 'app', label: 'https' },
      { from: 'app', to: 'mongo' },
      { from: 'app', to: 'kafka' },
    ],
  },
  {
    deploymentId: 'nwnd-dev',
    nodes: [
      {
        id: 'allinone',
        name: 'All-in-one dev box',
        role: 'application',
        host: 'nw-dev-01',
        x: 120,
        y: 120,
        stack: [
          { technology: 'Node.js', version: '24.21.0' },
          { technology: 'MongoDB', version: '8.2.12' },
          { technology: 'Apache Kafka', version: '3.8.1' },
          { technology: 'RHEL', version: '9.8' },
        ],
      },
    ],
    links: [],
  },
];

export const UPGRADE_ACTIONS: UpgradeAction[] = [
  {
    id: 'act-kafka',
    technology: 'Apache Kafka',
    cycle: '3.8',
    targetVersion: '4.1',
    status: 'PLANNED',
    plannedDate: '2026-10-15',
    assignee: 'DevOps Engineer',
    team: 'DevOps',
    jiraKey: 'LIME-1042',
    deploymentIds: ['acme-prod', 'nwnd-prod'],
  },
];
