"""Generates the endoflife.date slug -> Simple Icons lookup used by the registry.

Run when either catalogue changes:
    curl -s https://endoflife.date/api/v1/products/ -o prod.json
    curl -sL https://cdn.jsdelivr.net/npm/simple-icons@latest/data/simple-icons.json -o si.json
    py -3 gen_icons.py > product-icons.ts
"""

import io
import json
import re

products = json.load(io.open("prod.json", encoding="utf-8"))["result"]
raw = json.load(io.open("si.json", encoding="utf-8"))
icons = raw["icons"] if isinstance(raw, dict) and "icons" in raw else raw

def norm(value):
    return re.sub(r"[^a-z0-9]", "", value.lower())

lookup = {}
for icon in icons:
    lookup.setdefault(norm(icon["slug"]), icon)
    lookup.setdefault(norm(icon["title"]), icon)
    aliases = icon.get("aliases") or {}
    for key in ("aka", "dup", "old", "loc"):
        values = aliases.get(key) or []
        if not isinstance(values, list):
            continue
        for alias in values:
            if isinstance(alias, str):
                lookup.setdefault(norm(alias), icon)
            elif isinstance(alias, dict) and "title" in alias:
                lookup.setdefault(norm(alias["title"]), icon)

def match(product):
    """Exact name/label/alias first, then vendor prefixes, then trailing words."""
    for candidate in [product["name"], product.get("label") or ""] + (
        product.get("aliases") or []
    ):
        key = norm(candidate)
        if key in lookup:
            return lookup[key]

    segments = product["name"].split("-")

    for i in range(1, len(segments)):
        key = norm("".join(segments[i:]))
        if len(key) > 2 and key in lookup:
            return lookup[key]

    for i in range(len(segments) - 1, 0, -1):
        key = norm("".join(segments[:i]))
        if len(key) > 2 and key in lookup:
            return lookup[key]

    return None

rows = []
for product in sorted(products, key=lambda p: p["name"]):
    icon = match(product)
    if icon:
        rows.append((product["name"], icon["slug"], icon["hex"]))

print("/**")
print(" * endoflife.date slug -> Simple Icons slug and brand colour.")
print(" *")
print(" * Generated by scripts/gen-product-icons.py. Matched on name, label and")
print(" * alias, then by dropping vendor prefixes (amazon-rds-mysql is MySQL) and")
print(" * trailing words (ansible-core is Ansible). Products Simple Icons does not")
print(f" * carry are absent and render as a lettered tile: {len(rows)} of")
print(f" * {len(products)} products have a logo.")
print(" */")
print("export const PRODUCT_ICONS: Record<string, readonly [string, string]> = {")
for slug, icon_slug, hex_colour in rows:
    key = slug if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", slug) else f"'{slug}'"
    print(f"  {key}: ['{icon_slug}', '{hex_colour}'],")
print("};")
